### ISSUE TITLE
Parmetis patch checksum fails

### ISSUE THREAD

**Issue by jppelteret** [davydden/homebrew-dealiisuite#18]
It looks like the checksum for one of the patches (the first one) for Parmetis fails. If one downloads the raw file from Bitbucket then one gets some extra data (email header and footer information) on top of the patch itself. I'm not sure if it was always this way or not, so its hard to say whether the "raw" file download mechanism for bitbucket has changed or whether the patch itself has been modified. I think that we'll have to wait for Bitbucket / the PETSc guys to fix it.

**Comment by davydden** [comment]
it's seems the way to do is to change sha's, has been happening upstream https://github.com/Homebrew/homebrew-science/pull/3098
