### ISSUE TITLE
Installation without mkl

### ISSUE THREAD

**Issue by cpraveen** [davydden/homebrew-dealiisuite#2]
On a CentOS cluster, how to install if I dont have mkl. I suppose this is needed for lapack/blas. I have other implementations installed. This issue is from https://groups.google.com/d/msg/dealii/ouDRTLvZxhc/Apa2cH44DwAJ

**Comment by davydden** [comment]
If u do not set up blas/lapack environmental flags, BlasRequirement will test "-lblas -llapack", and if this fails it falls back to brewed Openblas.

The issue you gad was with tests of openblas. For some reason they fail for me on CentOS as well. I termporary disabled them.

If u do "brew update" you will have an updated formula and openblas installation should succeed.

**Comment by davydden** [comment]
If you have other blas/lapack, you should load the centos module and set the envirovmental variables accordingly (specify names, include dir and lib dir).

**Comment by cpraveen** [comment]
I have these files

```
[praveen@turing ~]$ ls /usr/lib64/libblas*
/usr/lib64/libblas.so.3  /usr/lib64/libblas.so.3.2  /usr/lib64/libblas.so.3.2.1
[praveen@turing ~]$ ls /usr/lib64/liblap*
/usr/lib64/liblapack.so.3    /usr/lib64/liblapack.so.3.2.1
/usr/lib64/liblapack.so.3.2
```

so I set

```
export HOMEBREW_BLASLAPACK_LIB="/usr/lib64"
export HOMEBREW_BLASLAPACK_INC="/usr/include"
```

But what is `HOMEBREW_BLASLAPACK_NAMES` ?

I am also not sure of the header files ? I cant find any ? Is there a separate package to be installed to get the header files ?

**Comment by davydden** [comment]
try `export HOMEBREW_BLASLAPACK_NAMES="blas;lapack"`. Eventually it would be good to have some auto-detection and search in the common places like `/usr/lib64/` but we are not yet there.

**Comment by davydden** [comment]
@cpraveen did you have any luck installing? Please update to the latest version, we fixed couple of bugs.

**Comment by cpraveen** [comment]
My cluster is missing blas/lapack header files, so could not use system blas. Now the openblas installs from brew. I have failure in the next package

```
==> Installing davydden/dealiisuite/metis dependency: cmake
==> Downloading http://www.cmake.org/files/v3.3/cmake-3.3.2.tar.gz
==> Downloading from https://cmake.org/files/v3.3/cmake-3.3.2.tar.gz
######################################################################## 100.0%
==> Downloading https://pypi.python.org/packages/source/s/sphinx_rtd_theme/sphin
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/cmake2015
Last 15 lines from /home/praveen/Logs/HOMEBREW/cmake/01.python:
python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/tmp/cmake20151104-10151-oco01r/cmake-3.3.2/sphinx
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named setuptools

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

These open issues may also help:
Eigen3 not found from Cmake https://github.com/Homebrew/homebrew/issues/44937
Enable debugging of cmake C++ library installed via homebrew https://github.com/Homebrew/homebrew/issues/44654
cmake builds fail on CLT-only with --env=std https://github.com/Homebrew/homebrew/issues/29101
```

**Comment by jppelteret** [comment]
I think that building `cmake` without docs works around this issue:

``` bash
brew install cmake --without-docs
```

**Comment by cpraveen** [comment]
I already have cmake version 3.4.0-rc2, why is it trying to install cmake ?

**Comment by jppelteret** [comment]
Does the full path for this version of cmake show when you run `which cmake`? If so, then we'll have to wait for @davydden to help with this issue...

**Comment by cpraveen** [comment]
Yes

```
[praveen@turing ~]$ which cmake
/usr/local/bin/cmake
```

**Comment by davydden** [comment]
@cpraveen you can try without specifying include dirs for blas/lapack. The test for working C blas/lapack tries to compile [this](https://github.com/davydden/homebrew-dealiisuite/blob/master/requirements/blas_requirement.rb#L84-L89) small program with [this](https://github.com/davydden/homebrew-dealiisuite/blob/master/requirements/blas_requirement.rb#L91) line. If it can't, it will fall-back to `openblas`.

w.r.t cmake, what is your version `cmake --version`? We do not have old cmake to test installation and thus in many formula like metis the minimum version is [specified to be 2.8](https://github.com/davydden/homebrew-dealiisuite/blob/master/metis.rb#L16). If yours is older you can try modifying these lines to something like `2.7` and see if it works. If it does, please create a pull-request with those changes so that we incorporate them.

**Comment by davydden** [comment]
@cpraveen just noticed that you have `3.4.0-rc2`. Can you try changing [this](https://github.com/davydden/homebrew-dealiisuite/blob/master/requirements/cmake_requirement.rb#L15) line to the two lines

```
cmake_version = Utils.popen_read("cmake", "--version").split(" ").last.split("-").first
ohai cmake_version
```

It could be that `Version` class in homebrew is confused by `3.4.0-rc2` instead of `3.4.0`. 
The second line just prints out the variable.

**Comment by cpraveen** [comment]
Thats not working. I have this output

```
[praveen@turing ~]$ cmake --version
cmake version 3.4.0-rc2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

and

```
[praveen@turing ~]$ brew install metis
==> Installing metis from davydden/homebrew-dealiisuite
==> (kitware.com/cmake).
==> Installing dependencies for davydden/dealiisuite/metis: cmake
==> Installing davydden/dealiisuite/metis dependency: cmake
==> Downloading http://www.cmake.org/files/v3.3/cmake-3.3.2.tar.gz
Already downloaded: /home/praveen/Cache/HOMEBREW/cmake-3.3.2.tar.gz
==> Downloading https://pypi.python.org/packages/source/s/sphinx_rtd_theme/sphin
Already downloaded: /home/praveen/Cache/HOMEBREW/cmake--sphinx_rtd_theme-0.1.8.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/cmake2015
Last 15 lines from /home/praveen/Logs/HOMEBREW/cmake/01.python:
python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/tmp/cmake20151104-20114-owznzm/cmake-3.3.2/sphinx
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named setuptools

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

These open issues may also help:
Eigen3 not found from Cmake https://github.com/Homebrew/homebrew/issues/44937
Enable debugging of cmake C++ library installed via homebrew https://github.com/Homebrew/homebrew/issues/44654
cmake builds fail on CLT-only with --env=std https://github.com/Homebrew/homebrew/issues/29101
```

**Comment by davydden** [comment]
ok, i see the problem. The cmake version was taken to be `==> (kitware.com/cmake).`

**Comment by davydden** [comment]
@cpraveen 
how about 

```
 cmake_version = Utils.popen_read("cmake", "--version").split(" ")[2]
```

(please keep the `ohai cmake_version` so that we see what it detects on your system).

**Comment by jppelteret** [comment]
@cpraveen Any updates on this? Did @davydden's suggestion work?

**Comment by cpraveen** [comment]
Sorry I lost forgot about this. So the latest suggestion is working. I installed metis now and it did not install cmake, instead it used my system cmake which is version 3.4.0-rc2

**Comment by jppelteret** [comment]
@cpraveen Great, thanks a lot. We'll keep this issue open for now. If you run into any other issues then feel free to post again. Otherwise, if the install is successful, could you please close the issue.

**Comment by cpraveen** [comment]
My blas/lapack does not have header files, though libraries are there. So I am letting brew install openblas. I will close this now.

**Comment by davydden** [comment]
on os-x one has to do something like `xcode-select --install` to get `/usr/include`. On Ubuntu one has to have `sudo apt-get libblas-dev liblapack-dev` (note the development version). 
Perhaps you need to do something like `yum install blas-devel lapack-devel`.
