### ISSUE TITLE
deal.II with threads

### ISSUE THREAD

**Issue by cpraveen** [davydden/homebrew-dealiisuite#20]
I see that dealii installation disables threads. I dont see any option to enable this in brew installation. Is this not supported ?

**Comment by davydden** [comment]
i don't recall why it's disabled. I think I had some issues compiling tbb on Centos. 

For now please try removing 

```
-DDEAL_II_FORCE_BUNDLED_THREADS=OFF
-DDEAL_II_WITH_THREADS=OFF
```

and see if that gets you the desired effect. 

Let's keep this issue opened.

**Comment by cpraveen** [comment]
I set both to ON and recompiled dealii. It is fine. I am also running my code with multiple threads.
