### ISSUE TITLE
Trilinos install failure on Ubuntu 15.10 with GCC 5.2.1

### ISSUE THREAD

**Issue by jppelteret** [davydden/homebrew-dealiisuite#22]
Fortran verification fails. See https://gist.github.com/jppelteret/0a02a41a1f86a9c0194a . It looks like the correct linking flags are not used (see http://stackoverflow.com/questions/5663083/linking-fortran-and-c-binaries-using-gcc ).

**Comment by davydden** [comment]
seems this is the same as https://github.com/davydden/homebrew-dealiisuite/issues/19

**Comment by jppelteret** [comment]
Yeah, and I don't understand how this could happen. On line 252 of [trilinos.rb](https://github.com/davydden/homebrew-dealiisuite/blob/master/trilinos.rb) there's a check that appends the right flags...

**Comment by davydden** [comment]
can you please try adding

```
-DTrilinos_EXTRA_LINK_FLAGS:STRING=-lgfortran
```

if that works, perhaps that's the correct way.

**Comment by jppelteret** [comment]
No, that didn't do anything. I see that on line 773 of the gist that -lgfortran is there. I think that it needs to go at the end of the line, and not the beginning, however I don't know how to make that happen.

**Comment by davydden** [comment]
i agree that it should go to the end... That's linking sequence issue... 

Do you want me to write to the trilinos mailing list with this issue?

p.s. I already about Zoltan2 compiling error for 12.4.2 (the most recent version).

**Comment by davydden** [comment]
a workaround would be to disable fortran for now...

**Comment by jppelteret** [comment]
Yes I suppose a bug report would be a good idea. I always wonder what they do in the cases that the bug report is provided for an older version (we're using 12.2.1 while they're now on 12.4.2)

**Comment by jppelteret** [comment]
I'll compile without fortran and let you know the result

**Comment by jppelteret** [comment]
Well, with fortran off its building. Success? I'll let you know tomorrow when all of this has finished building.

**Comment by davydden** [comment]
interestingly enough i just built 12.4.2 on my mac with gcc 5.3.0 without issues. Last time I was building trilinos 12.2.1 i have not had this issue either. I have no idea why sometimes it appears and sometimes not.

**Comment by jppelteret** [comment]
Similar for me last time I built Trilinos 12.2.1 on Ubuntu 14.04 with GCC 4.9.x - I didn't have the issue either! It seems like each combination of Trilinos and GCC versions will throw up a different set of issues. I wish that test their builds thoroughly.
